version: '2'

services:
  php:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/php-fpm:5.6-ol-7'
    ports:
      - 9000:9000
    volumes:
      - .:/app
